import mongoose from 'mongoose';
import { loadEnvConfig } from '@next/env';
import Hospital from '../models/Hospital';
import PoliceStation from '../models/PoliceStation';
import Driver from '../models/Driver';

loadEnvConfig(process.cwd());

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/sarathi-emergency';
const MONGODB_DB_NAME = process.env.MONGODB_DB_NAME || 'sarathi-emergency';

// Hospital data for Hyderabad and Secunderabad
const hospitalsData = [
  // Government Hospitals
  {
    name: 'Osmania General Hospital',
    address: 'Afzal Gunj, Hyderabad, Telangana 500012',
    latitude: 17.3850,
    longitude: 78.4867,
    phone: '040-24600146',
    email: 'osmania@ghmc.gov.in',
    specialties: ['General Medicine', 'Surgery', 'Emergency', 'Trauma', 'Cardiology'],
    bedsAvailable: 1500,
    totalBeds: 2000,
    type: 'government',
    isEmergencyAvailable: true,
    ambulanceCount: 15,
    rating: 4.2,
    city: 'Hyderabad',
    zone: 'Central',
  },
  {
    name: 'Gandhi Medical College Hospital',
    address: 'Musheerabad, Hyderabad, Telangana 500048',
    latitude: 17.4116,
    longitude: 78.5092,
    phone: '040-27505566',
    email: 'gandhimedical@telangana.gov.in',
    specialties: ['General Medicine', 'Surgery', 'Pediatrics', 'Orthopedics'],
    bedsAvailable: 800,
    totalBeds: 1000,
    type: 'government',
    isEmergencyAvailable: true,
    ambulanceCount: 8,
    rating: 4.0,
    city: 'Hyderabad',
    zone: 'North',
  },
  {
    name: 'Nizam\'s Institute of Medical Sciences',
    address: 'Panjagutta, Hyderabad, Telangana 500082',
    latitude: 17.4255,
    longitude: 78.4521,
    phone: '040-23489244',
    email: 'nimshyd@yahoo.com',
    specialties: ['Cardiology', 'Nephrology', 'Oncology', 'Neurology', 'Transplant'],
    bedsAvailable: 500,
    totalBeds: 800,
    type: 'government',
    isEmergencyAvailable: true,
    ambulanceCount: 10,
    rating: 4.5,
    city: 'Hyderabad',
    zone: 'Banjara Hills',
  },
  {
    name: 'Niloufer Hospital',
    address: 'Red Hills, Hyderabad, Telangana 500004',
    latitude: 17.3616,
    longitude: 78.4748,
    phone: '040-23311234',
    specialties: ['Pediatrics', 'Obstetrics', 'Gynecology', 'Neonatal Care'],
    bedsAvailable: 400,
    totalBeds: 600,
    type: 'government',
    isEmergencyAvailable: true,
    ambulanceCount: 6,
    rating: 3.9,
    city: 'Hyderabad',
    zone: 'Central',
  },
  {
    name: 'Tajdar Mahal Government Hospital',
    address: 'Salar Jung Colony, Hyderabad, Telangana 500024',
    latitude: 17.3950,
    longitude: 78.4789,
    phone: '040-24521011',
    specialties: ['General Medicine', 'Emergency', 'Surgery'],
    bedsAvailable: 200,
    totalBeds: 300,
    type: 'government',
    isEmergencyAvailable: true,
    ambulanceCount: 4,
    rating: 3.7,
    city: 'Hyderabad',
    zone: 'Central',
  },
  // Private Hospitals - Major Chains
  {
    name: 'Apollo Hospitals Jubilee Hills',
    address: 'Jubilee Hills, Road No. 72, Hyderabad, Telangana 500033',
    latitude: 17.4300,
    longitude: 78.4089,
    phone: '040-23607777',
    email: 'apollo.jubilee@apollohospitals.com',
    specialties: ['Cardiology', 'Neurology', 'Oncology', 'Orthopedics', 'Transplant', 'Emergency'],
    bedsAvailable: 350,
    totalBeds: 500,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 12,
    rating: 4.7,
    city: 'Hyderabad',
    zone: 'Jubilee Hills',
  },
  {
    name: 'Apollo Emergency Hospital',
    address: 'Jubilee Hills, Hyderabad, Telangana 500033',
    latitude: 17.4305,
    longitude: 78.4090,
    phone: '040-23608888',
    specialties: ['Emergency', 'Trauma', 'Critical Care'],
    bedsAvailable: 100,
    totalBeds: 100,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 8,
    rating: 4.8,
    city: 'Hyderabad',
    zone: 'Jubilee Hills',
  },
  {
    name: 'Yashoda Hospitals - Somajiguda',
    address: 'Raj Bhavan Road, Somajiguda, Hyderabad, Telangana 500082',
    latitude: 17.4275,
    longitude: 78.4589,
    phone: '040-45678900',
    email: 'info@yashodahospitals.com',
    specialties: ['Cardiology', 'Neurology', 'Oncology', 'Gastroenterology', 'Nephrology', 'Emergency'],
    bedsAvailable: 400,
    totalBeds: 550,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 10,
    rating: 4.6,
    city: 'Hyderabad',
    zone: 'Somajiguda',
  },
  {
    name: 'Yashoda Hospitals - Secunderabad',
    address: 'Alexander Road, Secunderabad, Telangana 500003',
    latitude: 17.4402,
    longitude: 78.4994,
    phone: '040-27718888',
    specialties: ['Cardiology', 'Surgery', 'Emergency', 'Orthopedics'],
    bedsAvailable: 300,
    totalBeds: 400,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 8,
    rating: 4.5,
    city: 'Secunderabad',
    zone: 'Central',
  },
  {
    name: 'Care Hospitals - Banjara Hills',
    address: 'Road No. 1, Banjara Hills, Hyderabad, Telangana 500034',
    latitude: 17.4123,
    longitude: 78.4234,
    phone: '040-30418888',
    email: 'care@carehospitals.com',
    specialties: ['Cardiology', 'Cardiac Surgery', 'Neurology', 'Neurosurgery', 'Emergency'],
    bedsAvailable: 350,
    totalBeds: 500,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 10,
    rating: 4.6,
    city: 'Hyderabad',
    zone: 'Banjara Hills',
  },
  {
    name: 'Sunshine Hospitals',
    address: 'Paradise Circle, Secunderabad, Telangana 500003',
    latitude: 17.4389,
    longitude: 78.5012,
    phone: '040-44555555',
    email: 'info@sunshinehospitals.com',
    specialties: ['Orthopedics', 'Joint Replacement', 'Spine Surgery', 'Emergency'],
    bedsAvailable: 250,
    totalBeds: 350,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 6,
    rating: 4.4,
    city: 'Secunderabad',
    zone: 'Central',
  },
  {
    name: 'Kamineni Hospitals',
    address: 'King Koti Road, Abids, Hyderabad, Telangana 500001',
    latitude: 17.3950,
    longitude: 78.4780,
    phone: '040-23232222',
    email: 'kamineni@kaminenihospitals.com',
    specialties: ['Cardiology', 'Oncology', 'Nephrology', 'Emergency'],
    bedsAvailable: 300,
    totalBeds: 400,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 8,
    rating: 4.3,
    city: 'Hyderabad',
    zone: 'Abids',
  },
  {
    name: 'Medicover Hospitals',
    address: 'Hitech City, Madhapur, Hyderabad, Telangana 500081',
    latitude: 17.4489,
    longitude: 78.3912,
    phone: '040-68334444',
    email: 'info@medicoverhospitals.com',
    specialties: ['Emergency', 'Critical Care', 'Cardiology', 'Neurology'],
    bedsAvailable: 200,
    totalBeds: 300,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 6,
    rating: 4.5,
    city: 'Hyderabad',
    zone: 'Hitech City',
  },
  {
    name: 'Gleneagles Global Hospital',
    address: 'Lake View Hils, Kukatpally, Hyderabad, Telangana 500072',
    latitude: 17.4940,
    longitude: 78.4010,
    phone: '040-44777111',
    email: 'global.hyd@gleneagleshospitals.com',
    specialties: ['Liver Transplant', 'Kidney Transplant', 'Oncology', 'Emergency'],
    bedsAvailable: 250,
    totalBeds: 350,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 6,
    rating: 4.5,
    city: 'Hyderabad',
    zone: 'Kukatpally',
  },
  {
    name: 'Continental Hospitals',
    address: 'Gachibowli, Hyderabad, Telangana 500032',
    latitude: 17.4689,
    longitude: 78.3512,
    phone: '040-67000000',
    email: 'info@continentalhospitals.com',
    specialties: ['Cardiology', 'Oncology', 'Neurology', 'Emergency'],
    bedsAvailable: 300,
    totalBeds: 450,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 8,
    rating: 4.6,
    city: 'Hyderabad',
    zone: 'Gachibowli',
  },
  {
    name: 'Aster Prime Hospital',
    address: 'Ameerpet, Hyderabad, Telangana 500016',
    latitude: 17.4370,
    longitude: 78.4312,
    phone: '040-45454545',
    specialties: ['Emergency', 'Cardiology', 'General Surgery'],
    bedsAvailable: 150,
    totalBeds: 200,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 4,
    rating: 4.2,
    city: 'Hyderabad',
    zone: 'Ameerpet',
  },
  {
    name: 'Pratian Hospital',
    address: 'Balkampet, Hyderabad, Telangana 500016',
    latitude: 17.4420,
    longitude: 78.4450,
    phone: '040-42044444',
    specialties: ['General Medicine', 'Emergency', 'Surgery'],
    bedsAvailable: 100,
    totalBeds: 150,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 3,
    rating: 4.0,
    city: 'Hyderabad',
    zone: 'Balkampet',
  },
  {
    name: 'Vijaya Hospital',
    address: 'Red Hills, Hyderabad, Telangana 500004',
    latitude: 17.3620,
    longitude: 78.4750,
    phone: '040-23392222',
    specialties: ['General Medicine', 'Surgery', 'Emergency'],
    bedsAvailable: 200,
    totalBeds: 300,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 4,
    rating: 4.1,
    city: 'Hyderabad',
    zone: 'Red Hills',
  },
  {
    name: 'Rao\'s Super Speciality Hospital',
    address: 'Saroornagar, Hyderabad, Telangana 500065',
    latitude: 17.3512,
    longitude: 78.5512,
    phone: '040-24054545',
    specialties: ['Cardiology', 'Neurology', 'Emergency'],
    bedsAvailable: 150,
    totalBeds: 200,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 4,
    rating: 4.3,
    city: 'Hyderabad',
    zone: 'Saroornagar',
  },
  // Specialty Hospitals
  {
    name: 'American Oncology Institute',
    address: 'Nizam\'s Institute of Medical Sciences, Hyderabad',
    latitude: 17.4260,
    longitude: 78.4520,
    phone: '040-23489999',
    specialties: ['Oncology', 'Radiation Therapy', 'Chemotherapy'],
    bedsAvailable: 100,
    totalBeds: 150,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 3,
    rating: 4.7,
    city: 'Hyderabad',
    zone: 'Panjagutta',
  },
  {
    name: 'Lakshika Cancer Hospital',
    address: 'King Koti, Hyderabad, Telangana 500001',
    latitude: 17.3940,
    longitude: 78.4790,
    phone: '040-23234455',
    specialties: ['Oncology', 'Cancer Surgery'],
    bedsAvailable: 80,
    totalBeds: 100,
    type: 'private',
    isEmergencyAvailable: false,
    ambulanceCount: 2,
    rating: 4.4,
    city: 'Hyderabad',
    zone: 'King Koti',
  },
  {
    name: 'Springleaf Heart Centre',
    address: 'Raj Bhavan Road, Somajiguda, Hyderabad',
    latitude: 17.4280,
    longitude: 78.4590,
    phone: '040-45674567',
    specialties: ['Cardiology', 'Cardiac Surgery', 'Interventional Cardiology'],
    bedsAvailable: 60,
    totalBeds: 80,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 3,
    rating:  4.8,
    city: 'Hyderabad',
    zone: 'Somajiguda',
  },
  {
    name: 'National Institute of Mental Health',
    address: 'Rajendranagar, Hyderabad, Telangana 500032',
    latitude: 17.4512,
    longitude: 78.3412,
    phone: '040-24015321',
    specialties: ['Psychiatry', 'Mental Health', 'De-addiction'],
    bedsAvailable: 500,
    totalBeds: 800,
    type: 'government',
    isEmergencyAvailable: true,
    ambulanceCount: 5,
    rating: 4.1,
    city: 'Hyderabad',
    zone: 'Rajendranagar',
  },
  // Secunderabad Hospitals
  {
    name: 'St. Theresa\'s Hospital',
    address: 'Sanath Nagar, Hyderabad, Telangana 500018',
    latitude: 17.4512,
    longitude: 78.4612,
    phone: '040-23701111',
    specialties: ['General Medicine', 'Surgery', 'Emergency'],
    bedsAvailable: 150,
    totalBeds: 200,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 4,
    rating: 4.0,
    city: 'Hyderabad',
    zone: 'Sanath Nagar',
  },
  {
    name: 'Mathrusri Hospital',
    address: 'Miyapur, Hyderabad, Telangana 500049',
    latitude: 17.4923,
    longitude: 78.3890,
    phone: '040-23054444',
    specialties: ['Emergency', 'General Medicine', 'Pediatrics'],
    bedsAvailable: 120,
    totalBeds: 150,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 4,
    rating: 4.2,
    city: 'Hyderabad',
    zone: 'Miyapur',
  },
  {
    name: 'Dr. Rao\'s Hospital',
    address: 'Kukatpally, Hyderabad, Telangana 500072',
    latitude: 17.4950,
    longitude: 78.4020,
    phone: '040-23151111',
    specialties: ['Gynecology', 'Obstetrics', 'Neonatal Care'],
    bedsAvailable: 100,
    totalBeds: 150,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 3,
    rating: 4.3,
    city: 'Hyderabad',
    zone: 'Kukatpally',
  },
  {
    name: 'Sreevani Hospital',
    address: 'Kothapet, Hyderabad, Telangana 500035',
    latitude: 17.3612,
    longitude: 78.5512,
    phone: '040-24085555',
    specialties: ['General Medicine', 'Emergency', 'Surgery'],
    bedsAvailable: 80,
    totalBeds: 100,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 3,
    rating: 4.1,
    city: 'Hyderabad',
    zone: 'Kothapet',
  },
  {
    name: 'Anupama Hospital',
    address: 'Dilsukhnagar, Hyderabad, Telangana 500060',
    latitude: 17.3689,
    longitude: 78.5212,
    phone: '040-24112222',
    specialties: ['Pediatrics', 'Gynecology', 'Emergency'],
    bedsAvailable: 100,
    totalBeds: 120,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 3,
    rating: 4.2,
    city: 'Hyderabad',
    zone: 'Dilsukhnagar',
  },
  {
    name: 'Malla Reddy Hospital',
    address: 'Suraram, Hyderabad, Telangana 500055',
    latitude: 17.4812,
    longitude: 78.4512,
    phone: '040-23734444',
    specialties: ['Emergency', 'Trauma', 'Orthopedics'],
    bedsAvailable: 150,
    totalBeds: 200,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 4,
    rating: 4.0,
    city: 'Hyderabad',
    zone: 'Suraram',
  },
  // More Area Hospitals
  {
    name: 'Olive Hospital',
    address: 'Miyapur X Road, Hyderabad, Telangana 500049',
    latitude: 17.4900,
    longitude: 78.3910,
    phone: '040-42444444',
    specialties: ['Multi-specialty', 'Emergency'],
    bedsAvailable: 200,
    totalBeds: 250,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 5,
    rating: 4.3,
    city: 'Hyderabad',
    zone: 'Miyapur',
  },
  {
    name: 'Himagiri Hospital',
    address: 'Gachibowli, Hyderabad, Telangana 500032',
    latitude: 17.4400,
    longitude: 78.3500,
    phone: '040-23001111',
    specialties: ['General Medicine', 'Surgery', 'Emergency'],
    bedsAvailable: 120,
    totalBeds: 150,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 3,
    rating: 4.1,
    city: 'Hyderabad',
    zone: 'Gachibowli',
  },
  {
    name: 'AIG Hospital',
    address: 'Gachibowli, Hyderabad, Telangana 500032',
    latitude: 17.4410,
    longitude: 78.3520,
    phone: '040-44884488',
    email: 'info@aighospitals.com',
    specialties: ['Gastroenterology', 'Hepatology', 'Endoscopy', 'Emergency'],
    bedsAvailable: 200,
    totalBeds: 300,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 5,
    rating: 4.5,
    city: 'Hyderabad',
    zone: 'Gachibowli',
  },
  {
    name: 'Citizens Hospital',
    address: 'Nallagandla, Hyderabad, Telangana 500019',
    latitude: 17.4600,
    longitude: 78.3212,
    phone: '040-67111111',
    specialties: ['Multi-specialty', 'Emergency', 'Trauma'],
    bedsAvailable: 180,
    totalBeds: 250,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 5,
    rating: 4.4,
    city: 'Hyderabad',
    zone: 'Nallagandla',
  },
  {
    name: 'Keshava Hospital',
    address: 'Kukatpally, Hyderabad, Telangana 500072',
    latitude: 17.4980,
    longitude: 78.4080,
    phone: '040-23110000',
    specialties: ['Orthopedics', 'Joint Replacement', 'Emergency'],
    bedsAvailable: 80,
    totalBeds: 100,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 3,
    rating: 4.2,
    city: 'Hyderabad',
    zone: 'Kukatpally',
  },
  {
    name: 'Archana Hospital',
    address: 'Miyapur, Hyderabad, Telangana 500049',
    latitude: 17.4890,
    longitude: 78.3880,
    phone: '040-23040000',
    specialties: ['Gynecology', 'Obstetrics', 'Pediatrics'],
    bedsAvailable: 100,
    totalBeds: 120,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 3,
    rating: 4.1,
    city: 'Hyderabad',
    zone: 'Miyapur',
  },
  // Additional hospitals
  {
    name: 'Bytes Hospital',
    address: 'Malakpet, Hyderabad, Telangana 500036',
    latitude: 17.3712,
    longitude: 78.4912,
    phone: '040-24521111',
    specialties: ['General Medicine', 'Emergency'],
    bedsAvailable: 100,
    totalBeds: 150,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 3,
    rating: 3.9,
    city: 'Hyderabad',
    zone: 'Malakpet',
  },
  {
    name: 'Vijetha Hospital',
    address: 'Lingoji Guda, Hyderabad, Telangana 500068',
    latitude: 17.4123,
    longitude: 78.4912,
    phone: '040-23702222',
    specialties: ['General Medicine', 'Surgery', 'Emergency'],
    bedsAvailable: 80,
    totalBeds: 100,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 2,
    rating: 4.0,
    city: 'Hyderabad',
    zone: 'Lingoji Guda',
  },
  {
    name: 'Mohan\'s Hospital',
    address: 'Vanasthalipuram, Hyderabad, Telangana 500070',
    latitude: 17.3312,
    longitude: 78.5612,
    phone: '040-24221111',
    specialties: ['Emergency', 'Trauma', 'Orthopedics'],
    bedsAvailable: 120,
    totalBeds: 150,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 4,
    rating: 4.1,
    city: 'Hyderabad',
    zone: 'Vanasthalipuram',
  },
  {
    name: 'Uppal Metro Multi Speciality Hospital',
    address: 'Uppal, Hyderabad, Telangana 500039',
    latitude: 17.4016,
    longitude: 78.5598,
    phone: '040-27202220',
    specialties: ['Emergency', 'Trauma', 'Cardiology', 'General Medicine'],
    bedsAvailable: 140,
    totalBeds: 180,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 4,
    rating: 4.3,
    city: 'Hyderabad',
    zone: 'Uppal',
  },
  {
    name: 'Boduppal Emergency Care Hospital',
    address: 'Boduppal, Hyderabad, Telangana 500092',
    latitude: 17.4141,
    longitude: 78.5783,
    phone: '040-27284444',
    specialties: ['Emergency', 'Orthopedics', 'General Surgery'],
    bedsAvailable: 90,
    totalBeds: 120,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 3,
    rating: 4.2,
    city: 'Hyderabad',
    zone: 'Boduppal',
  },
  {
    name: 'Ghatkesar LifeCare Hospital',
    address: 'Ghatkesar, Hyderabad, Telangana 501301',
    latitude: 17.4452,
    longitude: 78.6849,
    phone: '040-29555555',
    specialties: ['Emergency', 'Trauma', 'Critical Care', 'General Medicine'],
    bedsAvailable: 110,
    totalBeds: 150,
    type: 'private',
    isEmergencyAvailable: true,
    ambulanceCount: 4,
    rating: 4.4,
    city: 'Hyderabad',
    zone: 'Ghatkesar',
  },
];

// Police Station data for Hyderabad and Secunderabad
const policeStationsData = [
  // Hyderabad Police Commissionerate
  {
    name: 'Hyderabad City Police Commissionerate',
    address: 'Red Hills, Hyderabad, Telangana 500004',
    latitude: 17.3616,
    longitude: 78.4748,
    phone: '040-23221111',
    email: 'commissioner.hyd@tspolice.gov.in',
    jurisdiction: 'Entire Hyderabad City',
    type: 'commissionerate',
    city: 'Hyderabad',
    zone: 'Central',
    policeVehicles: 50,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Central Police Station',
    address: 'Gowliguda, Hyderabad, Telangana 500012',
    latitude: 17.3860,
    longitude: 78.4820,
    phone: '040-23244444',
    jurisdiction: 'Central Hyderabad',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Central',
    policeVehicles: 20,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'South Zone Police Station',
    address: 'Charminar, Hyderabad, Telangana 500002',
    latitude: 17.3615,
    longitude: 78.4745,
    phone: '040-24511111',
    jurisdiction: 'South Hyderabad',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'South',
    policeVehicles: 25,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'North Zone Police Station',
    address: 'Musheerabad, Hyderabad, Telangana 500048',
    latitude: 17.4110,
    longitude: 78.5090,
    phone: '040-27611111',
    jurisdiction: 'North Hyderabad',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'North',
    policeVehicles: 25,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'East Zone Police Station',
    address: 'Mallepally, Hyderabad, Telangana 500029',
    latitude: 17.4012,
    longitude: 78.4612,
    phone: '040-23311111',
    jurisdiction: 'East Hyderabad',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'East',
    policeVehicles: 20,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'West Zone Police Station',
    address: 'Kukatpally, Hyderabad, Telangana 500072',
    latitude: 17.4912,
    longitude: 78.4012,
    phone: '040-23111111',
    jurisdiction: 'West Hyderabad',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'West',
    policeVehicles: 25,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  // Specific Police Stations
  {
    name: 'Afzal Gunj Police Station',
    address: 'Afzal Gunj, Hyderabad, Telangana 500012',
    latitude: 17.3850,
    longitude: 78.4870,
    phone: '040-24611111',
    jurisdiction: 'Afzal Gunj Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Central',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Koti Police Station',
    address: 'Koti, Hyderabad, Telangana 500001',
    latitude: 17.3950,
    longitude: 78.4790,
    phone: '040-24711111',
    jurisdiction: 'Koti Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Central',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Abids Police Station',
    address: 'Abids, Hyderabad, Telangana 500001',
    latitude: 17.3970,
    longitude: 78.4780,
    phone: '040-23201111',
    jurisdiction: 'Abids Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Central',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Narayanaguda Police Station',
    address: 'Narayanaguda, Hyderabad, Telangana 500029',
    latitude: 17.4020,
    longitude: 78.4850,
    phone: '040-27511111',
    jurisdiction: 'Narayanaguda Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Central',
    policeVehicles: 12,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Himayatnagar Police Station',
    address: 'Himayatnagar, Hyderabad, Telangana 500029',
    latitude: 17.4010,
    longitude: 78.4910,
    phone: '040-27611111',
    jurisdiction: 'Himayatnagar Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'North',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Ashok Nagar Police Station',
    address: 'Ashok Nagar, Hyderabad, Telangana 500020',
    latitude: 17.4120,
    longitude: 78.5010,
    phone: '040-27711111',
    jurisdiction: 'Ashok Nagar Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'North',
    policeVehicles: 12,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Bashirbagh Police Station',
    address: 'Bashirbagh, Hyderabad, Telangana 500029',
    latitude: 17.4050,
    longitude: 78.4950,
    phone: '040-27551111',
    jurisdiction: 'Bashirbagh Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'North',
    policeVehicles: 10,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Jubilee Hills Police Station',
    address: 'Jubilee Hills, Hyderabad, Telangana 500033',
    latitude: 17.4310,
    longitude: 78.4090,
    phone: '040-23551111',
    jurisdiction: 'Jubilee Hills Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Jubilee Hills',
    policeVehicles: 20,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Banjara Hills Police Station',
    address: 'Banjara Hills, Hyderabad, Telangana 500034',
    latitude: 17.4130,
    longitude: 78.4230,
    phone: '040-23351111',
    jurisdiction: 'Banjara Hills Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Banjara Hills',
    policeVehicles: 18,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Somajiguda Police Station',
    address: 'Somajiguda, Hyderabad, Telangana 500082',
    latitude: 17.4270,
    longitude: 78.4590,
    phone: '040-45611111',
    jurisdiction: 'Somajiguda Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Somajiguda',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Panjagutta Police Station',
    address: 'Panjagutta, Hyderabad, Telangana 500082',
    latitude: 17.4250,
    longitude: 78.4520,
    phone: '040-23411111',
    jurisdiction: 'Panjagutta Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Panjagutta',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Ameerpet Police Station',
    address: 'Ameerpet, Hyderabad, Telangana 500016',
    latitude: 17.4370,
    longitude: 78.4310,
    phone: '040-23751111',
    jurisdiction: 'Ameerpet Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Ameerpet',
    policeVehicles: 18,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Sanath Nagar Police Station',
    address: 'Sanath Nagar, Hyderabad, Telangana 500018',
    latitude: 17.4510,
    longitude: 78.4610,
    phone: '040-23701111',
    jurisdiction: 'Sanath Nagar Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Sanath Nagar',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Begumpet Police Station',
    address: 'Begumpet, Hyderabad, Telangana 500016',
    latitude: 17.4410,
    longitude: 78.4710,
    phone: '040-27901111',
    jurisdiction: 'Begumpet Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Begumpet',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  // Secunderabad Police
  {
    name: 'Secunderabad Police Commissionerate',
    address: 'Padmarao Nagar, Secunderabad, Telangana 500025',
    latitude: 17.4310,
    longitude: 78.5010,
    phone: '040-27901111',
    email: 'commissioner.sec@tspolice.gov.in',
    jurisdiction: 'Entire Secunderabad',
    type: 'commissionerate',
    city: 'Secunderabad',
    zone: 'Central',
    policeVehicles: 40,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Secunderabad Cantonment Police Station',
    address: 'Secunderabad Cantonment, Telangana 500003',
    latitude: 17.4410,
    longitude: 78.5110,
    phone: '040-27801111',
    jurisdiction: 'Cantonment Area',
    type: 'police_station',
    city: 'Secunderabad',
    zone: 'Cantonment',
    policeVehicles: 20,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Paradise Police Station',
    address: 'Paradise, Secunderabad, Telangana 500003',
    latitude: 17.4390,
    longitude: 78.5010,
    phone: '040-27851111',
    jurisdiction: 'Paradise Area',
    type: 'police_station',
    city: 'Secunderabad',
    zone: 'Central',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Musheerabad Police Station',
    address: 'Musheerabad, Secunderabad, Telangana 500048',
    latitude: 17.4210,
    longitude: 78.5110,
    phone: '040-27601111',
    jurisdiction: 'Musheerabad Area',
    type: 'police_station',
    city: 'Secunderabad',
    zone: 'Musheerabad',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Warasiguda Police Station',
    address: 'Warasiguda, Secunderabad, Telangana 500061',
    latitude: 17.4150,
    longitude: 78.5210,
    phone: '040-27451111',
    jurisdiction: 'Warasiguda Area',
    type: 'police_station',
    city: 'Secunderabad',
    zone: 'Warasiguda',
    policeVehicles: 12,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  // Cyberabad Police Commissionerate
  {
    name: 'Cyberabad Police Commissionerate',
    address: 'Gachibowli, Hyderabad, Telangana 500032',
    latitude: 17.4410,
    longitude: 78.3510,
    phone: '040-23110000',
    email: 'commissioner.cyberabad@tspolice.gov.in',
    jurisdiction: 'Cyberabad Area',
    type: 'commissionerate',
    city: 'Hyderabad',
    zone: 'Cyberabad',
    policeVehicles: 60,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Kukatpally Police Station',
    address: 'Kukatpally, Hyderabad, Telangana 500072',
    latitude: 17.4910,
    longitude: 78.4010,
    phone: '040-23111111',
    jurisdiction: 'Kukatpally Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Kukatpally',
    policeVehicles: 25,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Miyapur Police Station',
    address: 'Miyapur, Hyderabad, Telangana 500049',
    latitude: 17.4890,
    longitude: 78.3890,
    phone: '040-23041111',
    jurisdiction: 'Miyapur Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Miyapur',
    policeVehicles: 20,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Gachibowli Police Station',
    address: 'Gachibowli, Hyderabad, Telangana 500032',
    latitude: 17.4400,
    longitude: 78.3500,
    phone: '040-23001111',
    jurisdiction: 'Gachibowli Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Gachibowli',
    policeVehicles: 20,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Madhapur Police Station',
    address: 'Madhapur, Hyderabad, Telangana 500081',
    latitude: 17.4490,
    longitude: 78.3910,
    phone: '040-23110000',
    jurisdiction: 'Madhapur Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Madhapur',
    policeVehicles: 25,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Financial District Police Station',
    address: 'Financial District, Gachibowli, Hyderabad',
    latitude: 17.4350,
    longitude: 78.3400,
    phone: '040-23002222',
    jurisdiction: 'Financial District',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Gachibowli',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  // Additional Police Stations
  {
    name: 'Rajendranagar Police Station',
    address: 'Rajendranagar, Hyderabad, Telangana 500032',
    latitude: 17.4510,
    longitude: 78.3410,
    phone: '040-24001111',
    jurisdiction: 'Rajendranagar Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Rajendranagar',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Shamirpet Police Station',
    address: 'Shamirpet, Hyderabad, Telangana 500078',
    latitude: 17.5210,
    longitude: 78.3110,
    phone: '040-23601111',
    jurisdiction: 'Shamirpet Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Shamirpet',
    policeVehicles: 10,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Kompally Police Station',
    address: 'Kompally, Hyderabad, Telangana 500014',
    latitude: 17.5110,
    longitude: 78.4810,
    phone: '040-23801111',
    jurisdiction: 'Kompally Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Kompally',
    policeVehicles: 12,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Ghatkesar Police Station',
    address: 'Ghatkesar, Hyderabad, Telangana 501301',
    latitude: 17.4510,
    longitude: 78.6810,
    phone: '040-22601111',
    jurisdiction: 'Ghatkesar Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Ghatkesar',
    policeVehicles: 10,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'L B Nagar Police Station',
    address: 'L B Nagar, Hyderabad, Telangana 500074',
    latitude: 17.3510,
    longitude: 78.5510,
    phone: '040-24201111',
    jurisdiction: 'L B Nagar Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'LB Nagar',
    policeVehicles: 18,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Saroornagar Police Station',
    address: 'Saroornagar, Hyderabad, Telangana 500065',
    latitude: 17.3510,
    longitude: 78.5510,
    phone: '040-24051111',
    jurisdiction: 'Saroornagar Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Saroornagar',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Dilsukhnagar Police Station',
    address: 'Dilsukhnagar, Hyderabad, Telangana 500060',
    latitude: 17.3690,
    longitude: 78.5210,
    phone: '040-24111111',
    jurisdiction: 'Dilsukhnagar Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Dilsukhnagar',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Chaitanyapuri Police Station',
    address: 'Chaitanyapuri, Hyderabad, Telangana 500060',
    latitude: 17.3610,
    longitude: 78.5310,
    phone: '040-24151111',
    jurisdiction: 'Chaitanyapuri Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Dilsukhnagar',
    policeVehicles: 12,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Vanasthalipuram Police Station',
    address: 'Vanasthalipuram, Hyderabad, Telangana 500070',
    latitude: 17.3310,
    longitude: 78.5610,
    phone: '040-24221111',
    jurisdiction: 'Vanasthalipuram Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Vanasthalipuram',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Malakpet Police Station',
    address: 'Malakpet, Hyderabad, Telangana 500036',
    latitude: 17.3710,
    longitude: 78.4910,
    phone: '040-24511111',
    jurisdiction: 'Malakpet Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Malakpet',
    policeVehicles: 12,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
  {
    name: 'Charminar Police Station',
    address: 'Charminar, Hyderabad, Telangana 500002',
    latitude: 17.3615,
    longitude: 78.4745,
    phone: '040-24521111',
    jurisdiction: 'Charminar Area',
    type: 'police_station',
    city: 'Hyderabad',
    zone: 'Charminar',
    policeVehicles: 15,
    emergencyContact: '100',
    isEmergencyAvailable: true,
  },
];

// Sample drivers data
const driversData = [
  {
    name: 'Ramesh Kumar',
    phone: '9701700001',
    email: 'ramesh.001@ambulance.com',
    licenseNumber: 'TS07-201900001',
    vehicleNumber: 'AP-15-AA-0001',
    vehicleType: 'Advanced Life Support',
    status: 'available',
    currentLatitude: 17.3850,
    currentLongitude: 78.4867,
    city: 'Hyderabad',
    zone: 'Central',
  },
  {
    name: 'Suresh Reddy',
    phone: '9701700002',
    email: 'suresh.002@ambulance.com',
    licenseNumber: 'TS07-201900002',
    vehicleNumber: 'AP-15-AA-0002',
    vehicleType: 'Basic Life Support',
    status: 'available',
    currentLatitude: 17.4300,
    currentLongitude: 78.4089,
    city: 'Hyderabad',
    zone: 'Jubilee Hills',
  },
  {
    name: 'Mahesh Singh',
    phone: '9701700003',
    email: 'mahesh.003@ambulance.com',
    licenseNumber: 'TS07-201900003',
    vehicleNumber: 'AP-15-AA-0003',
    vehicleType: 'Patient Transport',
    status: 'available',
    currentLatitude: 17.4410,
    currentLongitude: 78.5010,
    city: 'Secunderabad',
    zone: 'Central',
  },
  {
    name: 'Ravi Kumar',
    phone: '9701700004',
    email: 'ravi.004@ambulance.com',
    licenseNumber: 'TS07-201900004',
    vehicleNumber: 'AP-15-AA-0004',
    vehicleType: 'Advanced Life Support',
    status: 'available',
    currentLatitude: 17.4910,
    currentLongitude: 78.4010,
    city: 'Hyderabad',
    zone: 'Kukatpally',
  },
  {
    name: 'Anil Kumar',
    phone: '9701700005',
    email: 'anil.005@ambulance.com',
    licenseNumber: 'TS07-201900005',
    vehicleNumber: 'AP-15-AA-0005',
    vehicleType: 'Basic Life Support',
    status: 'available',
    currentLatitude: 17.4490,
    currentLongitude: 78.3910,
    city: 'Hyderabad',
    zone: 'Madhapur',
  },
  {
    name: 'Vijay Kumar',
    phone: '9701700006',
    email: 'vijay.006@ambulance.com',
    licenseNumber: 'TS07-201900006',
    vehicleNumber: 'AP-15-AA-0006',
    vehicleType: 'Advanced Life Support',
    status: 'available',
    currentLatitude: 17.3690,
    currentLongitude: 78.5210,
    city: 'Hyderabad',
    zone: 'Dilsukhnagar',
  },
  {
    name: 'Santosh Kumar',
    phone: '9701700007',
    email: 'santosh.007@ambulance.com',
    licenseNumber: 'TS07-201900007',
    vehicleNumber: 'AP-15-AA-0007',
    vehicleType: 'Basic Life Support',
    status: 'available',
    currentLatitude: 17.3610,
    currentLongitude: 78.4745,
    city: 'Hyderabad',
    zone: 'Charminar',
  },
  {
    name: 'Kumar Goud',
    phone: '9701700008',
    email: 'kumar.008@ambulance.com',
    licenseNumber: 'TS07-201900008',
    vehicleNumber: 'AP-15-AA-0008',
    vehicleType: 'Patient Transport',
    status: 'available',
    currentLatitude: 17.4120,
    currentLongitude: 78.4230,
    city: 'Hyderabad',
    zone: 'Banjara Hills',
  },
  {
    name: 'Prakash Rao',
    phone: '9701700009',
    email: 'prakash.009@ambulance.com',
    licenseNumber: 'TS07-201900009',
    vehicleNumber: 'AP-15-AA-0009',
    vehicleType: 'Advanced Life Support',
    status: 'available',
    currentLatitude: 17.4400,
    currentLongitude: 78.3500,
    city: 'Hyderabad',
    zone: 'Gachibowli',
  },
  {
    name: 'Deepak Kumar',
    phone: '9701700010',
    email: 'deepak.010@ambulance.com',
    licenseNumber: 'TS07-201900010',
    vehicleNumber: 'AP-15-AA-0010',
    vehicleType: 'Basic Life Support',
    status: 'available',
    currentLatitude: 17.4890,
    currentLongitude: 78.3890,
    city: 'Hyderabad',
    zone: 'Miyapur',
  },
];

async function seedDatabase() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI, { dbName: MONGODB_DB_NAME });
    console.log('Connected to MongoDB');

    // Clear existing data
    console.log('Clearing existing data...');
    await Hospital.deleteMany({});
    await PoliceStation.deleteMany({});
    await Driver.deleteMany({});
    console.log('Existing data cleared');

    // Seed Hospitals
    console.log('Seeding hospitals...');
    await Hospital.insertMany(hospitalsData);
    console.log(`Seeded ${hospitalsData.length} hospitals`);

    // Seed Police Stations
    console.log('Seeding police stations...');
    await PoliceStation.insertMany(policeStationsData);
    console.log(`Seeded ${policeStationsData.length} police stations`);

    // Seed Drivers
    console.log('Seeding drivers...');
    const normalizedDrivers = driversData.map((driver) => ({
      fullName: driver.name,
      phone: driver.phone,
      email: driver.email,
      licenseNumber: driver.licenseNumber,
      vehicleNumber: driver.vehicleNumber,
      password: 'Temp@12345',
      isAvailable: driver.status === 'available',
      currentLocation: {
        type: 'Point' as const,
        coordinates: [driver.currentLongitude, driver.currentLatitude] as [number, number],
      },
    }));
    await Driver.insertMany(normalizedDrivers);
    console.log(`Seeded ${normalizedDrivers.length} drivers`);

    console.log('Database seeding completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

// Run the seeding
seedDatabase();
